### ISSUE TITLE
Missing "symfony/finder" requirement

### ISSUE THREAD

**Issue by marius-wieschollek** [spatie/7to5#34]
I tried to install version 1.2.1 on a blank system. This failed because there seems to be a dependency on `symfony/finder` which is not covered by the composer.json.

### Steps to reproduce
- Download Composer from getcomposer.org and install it globally
- Run `composer global require spatie/7to5`
- Run `php7to5 convert {$directoryWithPHP7Code} {$destinationWithPHP5Code}`

### Expected result
Everything works

### Actual result
```
PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Finder\Finder' not found in /home/user/.config/composer/vendor/spatie/7to5/src/DirectoryConverter.php:98
Stack trace:
#0 /home/user/.config/composer/vendor/spatie/7to5/src/DirectoryConverter.php(85): Spatie\Php7to5\DirectoryConverter->copyDirectory('src/lib/', 'src/lib5')
#1 /home/user/.config/composer/vendor/spatie/7to5/src/Console/ConvertCommand.php(120): Spatie\Php7to5\DirectoryConverter->savePhp5FilesTo('src/lib5')
#2 /home/user/.config/composer/vendor/spatie/7to5/src/Console/ConvertCommand.php(79): Spatie\Php7to5\Console\ConvertCommand->convertPHPFilesInDirectory(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/user/.config/composer/vendor/symfony/console/Command/Command.php(252): Spatie\Php7to5\Console\ConvertCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/user/.config/composer/vendor/symfony/console/A in /home/user/.config/composer/vendor/spatie/7to5/src/DirectoryConverter.php on line 98
```

### Cause / Workaround
The package `symfony/finder` was not installed on my machine. Running  `composer global require symfony/finder` solved the problem.

**Comment by freekmurze** [comment]
Fixed in latest release
